### PR TITLE
Turn this extension into a library

### PR DESCRIPTION
**Pull request by JeroenDeDauw**

### CODE REVIEW

**Comment by JeroenDeDauw** [comment]
@s7eph4n MW Bootstrap is the only user of this extension/library at the moment right?

What about just putting the single class this package provides in MW Bootstrap? If there are no other things that already need the package, that would certainly simplify things. If something does need it, it can always duplicate the one class, and we could re-extract if it becomes more beneficial. YAGNI and all.

**Comment by JeroenDeDauw** [comment]
This occurred to me since at the moment I have not really tested my changes, since it is quite a pain to get the new version (including changed package dependencies) used by dependent extensions.

**Comment by Nikerabbit** [comment]
Why was all i18n deleted? Should I drop this from translatewiki.net?

**Comment by s7eph4n** [comment]
> What about just putting the single class this package provides in MW Bootstrap?

It started there before I took it out. I considered using it for FontAwesome, but at the moment that's not the case. So if you want, put it back in. 

Although I am not sure YAGNI fully applies in our context. In open-source development you usually look for what's available and re-combine what you find. This particularly in the case of MW extensions, where the task often is not to develop something completely new, but just to make some functionality available to the wiki user. So having the SCSS class in its own module gives it visibility. I don't think anybody who might have a need fo an SCSS RL module will go and search the Bootstrap extension for it.

**Comment by JeroenDeDauw** [comment]
> Why was all i18n deleted? Should I drop this from translatewiki.net?

I forgot about notifying you. Yes, please drop this repo from TWN, as there will not be any more content that need to be translated.

**Comment by JeroenDeDauw** [comment]
@s7eph4n can I be lazy here in some sense and let you decide? Do we turn this into a PHP lib or merge it into MW Boostrap?

**Comment by s7eph4n** [comment]
@JeroenDeDauw Really I don't mind either way. If it makes life easier for you, by all means pull it into Bootstrap. I'll leave a note on MW.org that the SCSS extension is not maintained anymore.

**Pull request merged**
